### PR TITLE
feat: importing and exporting utilities

### LINKED ISSUE #2: Proposal: Importing and Exporting
Another utility the is in [kv-toolbox](https://github.com/kitsonk/kv-toolbox) that could be generally useful and builds on the JSON serialization schema is the ability to import and export as [NDJSON](https://github.com/ndjson/ndjson-spec) (new line delimitated JSON) which is a format often used for logs and other situations where the data payload needs to be streamed.

I would propose adapting the following from kv-toolbox:

- `exportEntries(db, selector, options?)` - Would have overloads that returned a `ReadableStream<Uint8Array>`, `ReadableStream<string>` or a `Response` with a body which would stream the selected records.
- `importEntries(db, data, options?)` - Would be able to import entries from the data source which could be  `ReadableStream<Uint8Array>`, `Blob`/`File`, `ArrayBufferView`, `ArrayBuffer` or `string`.

This would allow users to provide the ability to provide interfaces to "download" data stored in a KV store as well as import it. Also because it would leverage the JSON schema it would allow implementors to do additional pre or post processing or procedural generation of data which can be stored in KV.

### PR DESCRIPTION
**Pull request by kitsonk**
Provides the ability to import and export Deno KV entries as new-line delimitated JSON in various forms.

Closes #2

### CODE REVIEW

**Review by kt3k — APPROVED** [review]
LGTM

**Comment by kitsonk** [comment]
Will it get merged then?

**Comment by kt3k** [comment]
I was waiting for the reaction from the core team, but now it looks fine to land

**Comment by kt3k** [comment]
Published as v0.1.2! https://jsr.io/@deno/kv-utils@0.1.2

**Pull request merged**
